blog/urls.py
from django.urls import path

from . import views
# from .views import (
#     BlogPostDetailView,
#     BlogPostListView,
#     BlogCreateFormView,
#     BlogPostUpdateView,
# )

app_name = 'blog'
urlpatterns = [
    path('', views.BlogPostListView.as_view(), name='blog-list'),
    path('show/<slug:slug>/', views.BlogPostDetailView.as_view(), name='post-detail'),
    path('edit/<slug:slug>/', views.BlogPostUpdateView.as_view(), name='post-update'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('new/', views.BlogCreateFormView.as_view(), name='post-create'),
]

blog_thing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('', include('blog.urls', namespace="blog")),
    path('baksiden/', admin.site.urls),
]

if settings.DEBUG:
    # Test mode
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.urls import reverse
from .utils import unique_slug_generator

User = settings.AUTH_USER_MODEL

class BlogPostQuerySet(models.QuerySet):
    def published(self):
        now = timezone.now()
        return self.filter(publish_date__lte=now)

class BlogPostManager(models.Manager):
    def get_queryset(self):
        return BlogPostQuerySet(self.model, using=self._db)

    def published(self):
        return self.get_queryset().published()

class Image(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to="image/", blank=False, null=True)

    def __str__(self):
        return self.image.url

class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

class BlogPost(models.Model):
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    slug = models.SlugField(max_length=150, unique=True, blank=True)
    title = models.CharField(max_length=100)
    content = models.TextField(null=True, blank=True)
    header_image = models.ForeignKey(Image, blank=False, null=True, on_delete=models.SET_NULL, related_name="header_image")
    content_images = models.ManyToManyField(Image, related_name="content_images", blank=True)
    categories = models.ManyToManyField(Category, blank=True)
    publish_date = models.DateTimeField(auto_now=False, auto_now_add=False, null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = BlogPostManager()

    class Meta:
        # ordering = ['-publish_date', '-updated', '-timestamp']
        ordering = ['-publish_date']
        base_manager_name = 'objects'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post-detail', args=[self.slug])

    def save(self, *args, **kwargs):
        self.slug = unique_slug_generator(self, self.title)
        super(BlogPost, self).save()

blog/forms.py
from django import forms
from pagedown.widgets import AdminPagedownWidget
from pagedown.widgets import PagedownWidget

from .models import BlogPost

class BlogPostAdminForm(forms.ModelForm):
    content = forms.CharField(widget=AdminPagedownWidget())

    class Meta:
        model = BlogPost
        fields = "__all__"

class BlogPostModelForm(forms.ModelForm):
    publish_date = forms.DateField(widget=forms.SelectDateWidget)
    content = forms.CharField(widget=PagedownWidget())

    class Meta:
        model = BlogPost
        fields = ['title', 'header_image', 'categories', 'content', 'publish_date']

    def clean_title(self, *args, **kwargs):
        title = self.cleaned_data.get("title")
        qs = BlogPost.objects.filter(title__iexact=title)
        if self.instance is not None:
            qs = qs.exclude(pk=self.instance.pk)
        if qs.exists():
            raise forms.ValidationError("This title exists, use another")
        return title

blog/views.py
from django.utils import timezone
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import FormView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import BlogPostModelForm
from .models import BlogPost, Image


class AboutView(TemplateView):
    template_name = "blog/about.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class ContactView(TemplateView):
    template_name = "blog/contact.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class BlogPostListView(ListView):
    model = BlogPost
    paginate_by = 20

    def get_queryset(self):
        return BlogPost.objects.all().published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['now'] = timezone.now()
        return context

class BlogCreateFormView(LoginRequiredMixin, FormView):
    template_name = "blog/create.html"
    form_class = BlogPostModelForm
    object = None

    # 403 if user is not logged in.
    raise_exception = True

    def get_success_url(self):
        return self.object.get_absolute_url()

    def form_valid(self, form):
        form.instance.author = self.request.user
        self.object = form.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['images'] = Image.objects.all()
        return context

class BlogPostDetailView(DetailView):
    model = BlogPost

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context

class BlogPostUpdateView(LoginRequiredMixin, UpdateView):
    model = BlogPost
    template_name = "blog/update.html"
    form_class = BlogPostModelForm

    # 403 if user is not logged in.
    raise_exception = True

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.save()
        return super().form_valid(form)

blog/templates/blog/about.html
{% extends "base.html" %}


{% block content %}
<div class="row">
    <div class="col col-lg-8 mx-auto">
        <h1>Om</h1>
        <p>Jeg er Jon-Martin, byråkrat og cybersikkerhetsentusiast.</p>
        <p>Du har nå kommet over min lille verden der jeg legger ut ting jeg surrer med om cybersikkherhet, teknologi, prosjekter og alt mulig annet jeg finner på.</p>
    </div>
</div>
{% endblock %}

blog/templates/blog/blogpost_detail.html
{% extends "base.html" %}

{% block head %}
<style>
  img.markdown-innhold {
    background-color: linen;
  }
</style>
{% endblock %}

{% load markdown_deux_tags %}

{% block content %}
<div class="row">
    <div class="col col-lg-8 mx-auto">
        {% if object.header_image %}
        <img src="{{ object.header_image.image.url }}" class="img-fluid" alt="Tittelbilde" style="width:100%;object-fit:cover;height:30vh">
        {% endif %}
        <h1 class="display-4">{{ object.title }}</h1>
        <p class="font-weight-bold text-uppercase">
        {% for category in object.categories.all %}
            <span style="padding-right:10px">{{ category }}</span>
        {% endfor %}
        </p>
        <p class="text-muted">{{ object.author }} - publisert {{ object.publish_date|date }}, sist endret {{ object.updated|date }}</p>
        <div class="markdown-innhold">
          <p>{{ object.content|markdown }}</p>
        </div>
        {% if request.user.is_authenticated %}
            <a href="{% url 'blog:post-update' slug=object.slug %}">Oppdater</a>
        {% endif %}
    </div>

    <div class="col col-lg-4 mx-auto">
        <h1>[å storme]</h1>
        <p>Jeg er Jon-Martin, byråkrat og cybersikkerhetsentusiast.</p>
        <p>Du har nå kommet over min lille verden der jeg legger ut ting jeg surrer med om cybersikkerhet, teknologi, prosjekter og alt mulig annet.</p>
    </div>
</div>
{% endblock %}

blog/templates/blog/blogpost_list.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col col-lg-8 mx-auto">
        {% for post in object_list %}
            {% include "blog/list-inline.html" with post=post %}
        {% endfor %}
    </div>

    <div class="col col-lg-4 mx-auto">
        <h1>[å storme]</h1>
        <p>Jeg er Jon-Martin, byråkrat og cybersikkerhetsentusiast.</p>
        <p>Du har nå kommet over min lille verden der jeg legger ut ting jeg surrer med om cybersikkerhet, teknologi, prosjekter og alt mulig annet.</p>
    </div>
</div>
{% endblock %}

blog/templates/blog/contact.html
{% extends "base.html" %}


{% block content %}
<div class="row">
    <div class="col col-lg-8 mx-auto">
        <h1>Kontakt</h1>
        <p>Jeg kan nås på jonmartp@uio.no<p>
    </div>
</div>
{% endblock %}

blog/templates/blog/create.html
{% extends "base.html" %}
{% block head %}
{{ form.media }}
<style>
.wmd-panel {
    width: 100%;
    margin: 0;
}
.wmd-button-bar {
    background: none;
}
.wmd-preview{
    width: 100%;
    max-height: 400px;
    overflow-y: auto;
    box-sizing: border-box;
    padding: 12px 14px;
    margin: 20px 0 0 0;
    border: 1px solid #eee;
    border-radius: 4px;
    background: #f8f8f8;
}
</style>
{% endblock %}
{% block head_title %}{{ title }}{% endblock %}
{% block content %}
{% load crispy_forms_tags %}
{% load markdown_deux_tags %}
<div class="row">
    <div class="col-8 mx-auto">
        <h1>Create new post</h1>
        <form method="POST" enctype="multipart/form-data">{% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-dark">Publiser</button>
        </form>
    </div>
    <div class="col-4 mx-auto">
      <div style="max-height: 800px;overflow: scroll;">
      {% for image in images %}
        <img src="{{ image.image.url }}" class="img-fluid" alt="{{ image.image.url }}">
        <p><small>{{ image.image.url }}</small></p>
      {% endfor %}
      </div>
      {% markdown_cheatsheet %}
    </div>
</div>
{% endblock %}

blog/templates/blog/list-inline.html
{% load markdown_deux_tags %}
<div class="card mb-3">
    {% if post.header_image %}
    <img src="{{post.header_image.image.url}}" class="card-img-top" style="width:100%;object-fit:cover;height:20vh">
    {% else %}
    <div class="card-header">
        Post
    </div>
    {% endif %}
  <div class="card-body">
    <h1 class="card-title">{{ post.title }}</h1>
    <p class="card-subtitle text-muted">{{ post.author.get_full_name }} - publisert {{ post.publish_date|date }}, sist endret for {{ post.updated|timesince }} siden</p>
    <p>{{ post.content|markdown|truncatewords_html:50 }}</p>
    <p><small class="font-weight-bold text-uppercase">
      {% for category in post.categories.all %}
          <span style="padding-right:10px">{{ category }}</span>
      {% endfor %}
    </small></p>
    <a href="{% url 'blog:post-detail' slug=post.slug %}" class="card-link">Les mer</a>
  </div>
</div>

blog/templates/blog/update.html
{% extends "base.html" %}
{% block head %}
{{ form.media }}
<style>
.wmd-panel {
    width: 100%;
    margin: 0;
}
.wmd-button-bar {
    background: none;
}
.wmd-preview{
    width: 100%;
    max-height: 400px;
    overflow-y: auto;
    box-sizing: border-box;
    padding: 12px 14px;
    margin: 20px 0 0 0;
    border: 1px solid #eee;
    border-radius: 4px;
    background: #f8f8f8;
}
</style>
{% endblock %}
{% block head_title %}{{ title }}{% endblock %}
{% block content %}
{% load crispy_forms_tags %}
{% load markdown_deux_tags %}
<div class="row">
    <div class="col-8 mx-auto">
        <h1>Update post</h1>
        <p>Author: {{ object.author }}</p>
        <form method="POST">{% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-dark">Oppdater</button>
        </form>
    </div>
    <div class="col-4 mx-auto">
      <div style="max-height: 800px;overflow: scroll;">
      {% for image in images %}
        <img src="{{ image.image.url }}" class="img-fluid" alt="{{ image.image.url }}">
        <p><small>{{ image.image.url }}</small></p>
      {% endfor %}
      </div>
      {% markdown_cheatsheet %}
    </div>
</div>

{% endblock %}

blog/templates/blog_post_create.html
{% extends "base.html" %}
{% block head_title %}{{ title }}{% endblock %}
{% block content %}

<div class = 'container'>
    <div class="row">
        <div class="col-6 mx-auto">
            <h1>Create new post</h1>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog_post_detail.html
{% extends "base.html" %}


{% block content %}
<div class = 'container'>
    <div class="row">
        <div class="col-6 mx-auto">
            <h1>{{ object.title }}</h1>
            <p>{{ object.content }}</p>
            <p>Todays date: {{ now|date:'j.b Y -- c' }}</p>
            <!-- https://docs.djangoproject.com/en/2.2/ref/templates/builtins/#date -->
        </div>
    </div>
</div>


{% endblock %}

blog/templates/blog_post_list.html
{% extends "base.html" %}

{% block content %}
<div class = 'container'>
    <div class="row">
        <div class="col-6 mx-auto">
            <h1>Blog post list:</h1>
            {% for post in object_list %}
            <li>
                <a href="{% url 'blog:post-detail' slug=post.slug %}">{{ post.title }}</a>
            </li>

            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

templates/base.html
{% load static from staticfiles %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    {% block head %}
    {% endblock %}

    <title>{% block head_title %}storme.no{% endblock %}</title>
  </head>


  <body>
    {% include "navbar.html" %}

    <div class="container mt-3 mb-3">
    {% block content %}
    {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <script>
    $(document).ready(function(){
      $(".markdown-innhold img").each(function(){
        $(this).addClass("img-fluid")
      })
    })
    $(document).ready(function(){
      $(".markdown-innhold blockquote").each(function(){
        $(this).addClass("blockquote");
                               $(this).addClass("border");
                               $(this).addClass("border-success");
                               $(this).addClass("rounded");
                               $(this).addClass("p-3");
      })
    })
    </script>
  </body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-md bg-dark navbar-dark sticky-top">
  <a class="navbar-brand" href="{% url 'blog:blog-list' %}">[å storme]</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:blog-list' %}">blog</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:about' %}">om</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:contact' %}">kontakt</a>
      </li>
    </ul>
  </div>
</nav>